spring.data.mongodb.database=journaldb
spring.data.mongodb.uri=mongodb+srv://shikhachakrawarty:Mypassword@cluster0.kh0tq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
server.port=8080

weather.api.key=781db59ae539bf56c0ad7dca047ebdaf